Refresh repo on deletion of Storage Accounts. Plus some cosmetic changes and updates.
FINTLabs/azurerator pull request #11
Opened 2024-04-26 09:42 UTC by sondre81

- Set up functionallity for repo refresh when account is deleted.
- Changed code to reflect on environments in logs.
- Changed deployment file to use matrix to reduce lines and improve readability.
- Updated actions to newer versions that supports Node.js 20
- Added and re-wrote tests to use jUnit and Mockito.

2024-09-30 11:15 UTC, murillio4 requested changes
Litt logikk endringer som må ses på :)

2024-09-30 11:15 UTC, murillio4 commented on src/main/java/no/fintlabs/azure/storage/StorageResourceRepository.java
> +                .forEach(storageResource -> log.debug("Storage account name: {}", storageResource.getStorageAccountName()));
Disse kan bruke `getStorageResourcesByEnvironment`

2024-09-30 11:15 UTC, murillio4 commented on src/main/java/no/fintlabs/azure/storage/StorageResourceRepository.java
> +    }
Logikken her henger ikke helt sammen. Først hentes alle eksisterende ressurser, og deretter itereres det over dem for å hente alle ressursene på nytt for hver enkelt ressurs. For eksempel, hvis du har 5 ressurser i cache, vil du hente alle ressursene på nytt 5 ganger – én gang for hver ressurs.

Dette trenger kun å være  `loadStorageResources()`

2024-09-30 11:15 UTC, murillio4 commented on src/main/java/no/fintlabs/azure/storage/StorageResourceRepository.java
> +                .count();
Her kan du bruke ` getStorageResourcesByEnvironment().count()`

2024-09-30 11:15 UTC, murillio4 commented on src/main/resources/application.yaml
> +    root: info
Root info er litt mye. Bruk heller `warning` eller `error`

2024-09-30 11:15 UTC, murillio4 commented on src/main/resources/application.yaml
> +    environment: local-dev
Fjern denne

2024-09-30 11:15 UTC, murillio4 commented on src/test/java/no/fintlabs/azure/storage/StorageResourceRepositoryTest.java
> +    }
Se kommentaren min i `StorageResourceRepository` om refresh av resources

2024-10-01 09:50 UTC, sondre81 commented on src/main/java/no/fintlabs/azure/storage/StorageResourceRepository.java
> +                .count();
Ender med å bruke .size() etter forslag fra intelliJ, færre gule linjer og gjenspeiler navnet.

2024-11-26 16:15 UTC, murillio4 approved these changes

2024-11-26 16:16 UTC, merged