Fla 130 ability to remove blobs
FINTLabs/azurerator pull request #12
Opened 2024-06-24 08:59 UTC by sondre81

Added ability to remove storage blobs after a given time set in the crd.
Wrote unit tests.

2024-06-24 09:44 UTC, sondre81 commented
Bør kansje endre Deploymenten til å kun gjelde Alpha til å begynne med? Greit å sjekke at ting ikke krasjer før man kaster det ut i Beta/Api.

2024-09-30 10:46 UTC, murillio4 requested changes
Hvis du får ryddet opp i dette, ser på kommentaren min om navn på lifespan-labelen, legger til validering av minimum og maksimum for lifespanDays, og tester dette, så er dette på god vei til å bli bra! :)

2024-09-30 10:46 UTC, murillio4 commented on src/main/java/no/fintlabs/azure/TagNames.java
> +    public static final String TAG_LIFESPAN = "60L";
Should tag name be `60L`? Or is `60L` the value?

2024-09-30 10:46 UTC, murillio4 commented on src/main/java/no/fintlabs/azure/storage/StorageAccountService.java
> +                .withTag(TAG_LIFESPAN, "60L")
Burde denne være satt til `lifespanDays`?

2024-09-30 10:46 UTC, murillio4 commented on src/main/java/no/fintlabs/azure/storage/StorageResource.java
> +        long lifespanDays = Long.parseLong(storageAccount.tags().getOrDefault(TAG_LIFESPAN, "60L"));
`60L` burde vært trukket ut som en konstant.

2024-10-09 12:54 UTC, murillio4 submitted a review, later dismissed

2024-10-09 12:54 UTC, murillio4 commented on src/main/java/no/fintlabs/azure/storage/StorageAccountService.java
> +                .withTag(TAG_LIFESPAN_DAYS, String.valueOf(lifespanDays))
Er det snakk om lifespan på storage accounten, eller lifespan på blobs i storage accounten?

Blob storage støtter lifespan/retention på blobs, men om man ønsker å sette denne til en custom verdi kan ikke dette gjøres gjennom tags. Det må lages en ny lifecycle rule hvor man setter lifespan på blobs.

Tenker det er fint å bevare lifespan tagen på storage accounten slik at det blir lettere for oss å søke, etc...

https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-policy-configure?tabs=azure-portal

2024-10-09 12:54 UTC, murillio4 commented on src/main/java/no/fintlabs/azure/storage/StorageAccountService.java
> +                .withTag(TAG_LIFESPAN_DAYS, String.valueOf(lifespanDays))
Et annet spm er om man alltid vil ha lifespan? Skal den være optional? Så om den ikke er satt vil vi ikke opprette en lifespan regel.

2024-10-09 12:54 UTC, murillio4 commented on src/test/java/no/fintlabs/azure/storage/blob/BlobContainerServiceTest.java
Denne må vi rydde litt opp i. Jeg tenker vi bruker [Azurite](https://github.com/Azure/Azurite) for dette. Jeg kan sette opp

2024-11-26 15:17 UTC, merged